<?php

#MASUKAN COOKIE CFDUID MILIK KALIAN!!!
$cfduid = "xxxxxxxxx";

#MASUKAN COOKIE PHPSESSID MILIK KALIAN!!!
$PHPSESSID = "xxxxxxxx";

#MASUKAN COOKIE GA MILIK KALIAN!!!
$ga = "xxxxxxxxx";

#MASUKAN COOKIE GID MILIK KALIAN!!!
$gid = "xxxxxxxxx";
